
    const translations = {
      en: {
        title: "Doctor Vinyl Records",
        nav_home: "Home",
        nav_records: "Records",
        nav_specials: "Specials",
        nav_about: "About",
        nav_contact: "Contact",
        nav_sales: "Sales",
        nav_login: "Login",
        search_placeholder: "Search...",
        sales_title: "Sales",
        sale_badge: "SALE",
        add_to_cart: "Add to cart",
        hero_title: "Doctor Vinyl Records",
        hero_subtitle: "Vinyl specialist in Brussels – New & second-hand records, specials & more",
        records_title: "All Records",
        specials_title: "Specials & Own Releases",
        about_title: "About / News",
        about_text: "DOCTOR VINYL, situated in the heart of Brussels, stands as one of the pioneering vinyl shops in Belgium, specialized in electronic music. A beacon for electronic music enthusiasts, our small and cozy shop is a haven for those seeking the authentic warm analog sounds. At Doctor Vinyl, we pride ourselves on curating a collection of used and occasionally new vinyl that is meticulously organized and carefully selected. As explorers of fresh grooves, we offer a diverse array of subcategories within electronic music, including House, Techno, D&B, Nu Beat, Industrial, experimental, and everything in between. Our shop is not just a place to buy vinyl; it's a space where music lovers come together to share their passion. Our friendly and knowledgeable staff are here to guide you and ensuring that each visit is a unique and enriching experience. As one of the first establishments of its kind in Belgium, Doctor Vinyl has become a cornerstone in the cultural tapestry of Brussels. Step into our world, where the crackle of vinyl and the pulse of electronic beats merge to create an unforgettable shopping experience.",
        contact_title: "Contact",
        contact_address: "Groot Eiland 1\n1000 Brussels",
        contact_phone: "+32 476 71 75 40",
        contact_mail: "info@doctorvinyl.be",
        cart_title: "Shopping Cart",
        cart_total: "Total:",
        cart_clear: "Clear Cart",
        checkout: "Checkout",
        login_title: "Login",
        login_username: "Email",
        login_password: "Password",
        login_btn: "Login",
        register_link: "No account? Register",
        register_title: "Register",
        register_username: "Email",
        register_password: "Password",
        register_password_confirm: "Confirm Password",
        register_lastname: "Last Name",
        register_firstname: "First Name",
        register_street: "Street",
        register_number: "Number",
        register_app: "App.",
        register_postal: "Postal Code",
        register_city: "City",
        register_country: "Country",
        register_address: "Address",
        register_btn: "Register",
        register_username_placeholder: "Email",
        register_password_placeholder: "Password",
        register_password_confirm_placeholder: "Confirm Password",
        register_lastname_placeholder: "Last Name",
        register_firstname_placeholder: "First Name",
        register_street_placeholder: "Street",
        register_number_placeholder: "Number",
        register_app_placeholder: "App.",
        register_postal_placeholder: "e.g. 1000",
        register_city_placeholder: "City",
        register_country_placeholder: "Country",
        my_account_btn: "My Account",
        my_account_title: "My Account",
        my_account_save: "Save",
        address_title: "Address Details",
        address_label: "Address",
        address_save: "Save",
        order_overview: "Order Overview",
        shipping_to: "Shipping to",
        subtotal: "Subtotal",
        shipping_cost: "Shipping",
        order_total: "Total",
        free_shipping: "🎉 Free shipping!",
        free_shipping_info: "💡 Add {amount} more for free shipping!",
        confirm_order: "✅ Confirm Order",
        edit_address: "✏️ Edit Address",
        order_confirmed: "🎉 Order Confirmed!",
        order_number: "Order Number",
        order_success_text: "Your order has been received and is being processed.",
        email_confirmation: "📧 A confirmation will be sent to:",
        shipping_info_text: "📦 Shipping:",
        close_btn: "Close"
      },
      nl: {
        title: "Doctor Vinyl Records",
        nav_home: "Home",
        nav_records: "Platen",
        nav_specials: "Specials",
        nav_about: "Over",
        nav_contact: "Contact",
        nav_sales: "Aanbiedingen",
        nav_login: "Inloggen",
        search_placeholder: "Zoeken...",
        sales_title: "Aanbiedingen",
        sale_badge: "ACTIE",
        add_to_cart: "In winkelmand",
        hero_title: "Doctor Vinyl Records",
        hero_subtitle: "Vinyl specialist in Brussel – Nieuwe & tweedehands platen, specials & meer",
        records_title: "Alle Platen",
        specials_title: "Specials & Eigen Releases",
        about_title: "Over / Nieuws",
        about_text: "DOCTOR VINYL, gelegen in het hart van Brussel, is één van de pionierende vinylwinkels in België, gespecialiseerd in elektronische muziek. Een baken voor liefhebbers van elektronische muziek, onze kleine en gezellige shop is een toevluchtsoord voor wie op zoek is naar de authentieke warme analoge sound. Bij Doctor Vinyl zijn we trots op onze collectie gebruikte en af en toe nieuwe vinyl, zorgvuldig geselecteerd en overzichtelijk georganiseerd. Als ontdekkers van nieuwe grooves bieden we een breed scala aan subcategorieën binnen de elektronische muziek, waaronder House, Techno, D&B, Nu Beat, Industrial, experimenteel en alles daartussenin. Onze winkel is niet alleen een plek om vinyl te kopen; het is een ontmoetingsplaats waar muziekliefhebbers samenkomen om hun passie te delen. Ons vriendelijke en deskundige team begeleidt je graag en zorgt ervoor dat elk bezoek uniek en verrijkend is. Als één van de eerste zaken in zijn soort in België is Doctor Vinyl een vaste waarde in het culturele weefsel van Brussel. Stap binnen in onze wereld, waar het geknisper van vinyl en de puls van elektronische beats samenkomen voor een onvergetelijke shopervaring.",
        contact_title: "Contact",
        contact_address: "Groot Eiland 1\n1000 Brussel",
        contact_phone: "+32 476 71 75 40",
        contact_mail: "info@doctorvinyl.be",
        cart_title: "Winkelmandje",
        cart_total: "Totaal:",
        cart_clear: "Winkelmand legen",
        checkout: "Afrekenen",
        login_title: "Inloggen",
        login_username: "E-mail",
        login_password: "Wachtwoord",
        login_btn: "Inloggen",
        register_link: "Nog geen account? Registreer",
        register_title: "Registreren",
        register_username: "E-mail",
        register_password: "Wachtwoord",
        register_password_confirm: "Wachtwoord bevestigen",
        register_lastname: "Achternaam",
        register_firstname: "Voornaam",
        register_street: "Straat",
        register_number: "Nummer",
        register_app: "App.",
        register_postal: "Postcode",
        register_city: "Stad",
        register_country: "Land",
        register_address: "Adres",
        register_btn: "Registreer",
        register_username_placeholder: "E-mail",
        register_password_placeholder: "Wachtwoord",
        register_password_confirm_placeholder: "Wachtwoord bevestigen",
        register_lastname_placeholder: "Achternaam",
        register_firstname_placeholder: "Voornaam",
        register_street_placeholder: "Straat",
        register_number_placeholder: "Nummer",
        register_app_placeholder: "App.",
        register_postal_placeholder: "bijv. 1000",
        register_city_placeholder: "Stad",
        register_country_placeholder: "Land",
        my_account_btn: "Mijn Account",
        my_account_title: "Mijn Account",
        my_account_save: "Opslaan",
        address_title: "Adresgegevens",
        address_label: "Adres",
        address_save: "Opslaan",
        order_overview: "Bestelling overzicht",
        shipping_to: "Verzending naar",
        subtotal: "Subtotaal",
        shipping_cost: "Verzendkosten",
        order_total: "Totaal",
        free_shipping: "🎉 Gratis verzending!",
        free_shipping_info: "💡 Nog €{amount} voor gratis verzending!",
        confirm_order: "✅ Bestelling bevestigen",
        edit_address: "✏️ Adres wijzigen",
        order_confirmed: "🎉 Bestelling bevestigd!",
        order_number: "Bestelnummer",
        order_success_text: "Je bestelling is ontvangen en wordt verwerkt.",
        email_confirmation: "📧 Een bevestiging wordt verstuurd naar:",
        shipping_info_text: "📦 Verzending:",
        close_btn: "Sluiten"
      },
      fr: {
        title: "Doctor Vinyl Records",
        nav_home: "Accueil",
        nav_records: "Disques",
        nav_specials: "Spéciaux",
        nav_about: "À propos",
        nav_contact: "Contact",
        nav_sales: "Promos",
        nav_login: "Connexion",
        search_placeholder: "Recherche...",
        sales_title: "Promos",
        sale_badge: "PROMO",
        add_to_cart: "Ajouter au panier",
        hero_title: "Doctor Vinyl Records",
        hero_subtitle: "Spécialiste vinyle à Bruxelles – Nouveaux & occasions, spéciaux & plus",
        records_title: "Tous les Disques",
        specials_title: "Spéciaux & Propres Sorties",
        about_title: "À propos / News",
        about_text: "Doctor Vinyl est une référence à Bruxelles pour les amateurs de vinyles. Vous y trouverez non seulement une large sélection de disques, mais aussi des sorties propres, des spéciaux, des événements et plus encore. Restez informé de nos dernières nouvelles et événements !",
        about_text: "DOCTOR VINYL, situé au cœur de Bruxelles, est l’un des magasins de vinyles pionniers en Belgique, spécialisé dans la musique électronique. Véritable phare pour les passionnés de musique électronique, notre petite boutique chaleureuse est un havre pour ceux qui recherchent le son analogique authentique et chaleureux. Chez Doctor Vinyl, nous sommes fiers de proposer une collection de vinyles d’occasion et parfois neufs, soigneusement organisée et sélectionnée. Explorateurs de nouveaux grooves, nous offrons une grande diversité de sous-catégories dans la musique électronique, dont House, Techno, D&B, Nu Beat, Industrial, expérimental, et tout ce qui s’y rattache. Notre magasin n’est pas seulement un lieu d’achat, c’est un espace où les amateurs de musique se retrouvent pour partager leur passion. Notre équipe, accueillante et experte, est là pour vous guider et faire de chaque visite une expérience unique et enrichissante. En tant que l’un des premiers établissements de ce type en Belgique, Doctor Vinyl est devenu une pierre angulaire du tissu culturel bruxellois. Entrez dans notre univers, où le crépitement du vinyle et le rythme des beats électroniques fusionnent pour une expérience shopping inoubliable.",
        contact_title: "Contact",
        contact_address: "Groot Eiland 1\n1000 Bruxelles",
        contact_phone: "+32 476 71 75 40",
        contact_mail: "info@doctorvinyl.be",
        cart_title: "Panier",
        cart_total: "Total :",
        cart_clear: "Vider le panier",
        checkout: "Commander",
        login_title: "Connexion",
        login_username: "E-mail",
        login_password: "Mot de passe",
        login_btn: "Connexion",
        register_link: "Pas de compte ? Inscrivez-vous",
        register_title: "Inscription",
        register_username: "E-mail",
        register_password: "Mot de passe",
        register_password_confirm: "Confirmer le mot de passe",
        register_lastname: "Nom de famille",
        register_firstname: "Prénom",
        register_street: "Rue",
        register_number: "Numéro",
        register_app: "App.",
        register_postal: "Code postal",
        register_city: "Ville",
        register_country: "Pays",
        register_address: "Adresse",
        register_btn: "Inscription",
        register_username_placeholder: "E-mail",
        register_password_placeholder: "Mot de passe",
        register_password_confirm_placeholder: "Confirmer le mot de passe",
        register_lastname_placeholder: "Nom de famille",
        register_firstname_placeholder: "Prénom",
        register_street_placeholder: "Rue",
        register_number_placeholder: "Numéro",
        register_app_placeholder: "App.",
        register_postal_placeholder: "ex. 1000",
        register_city_placeholder: "Ville",
        register_country_placeholder: "Pays",
        my_account_btn: "Mon Compte",
        my_account_title: "Mon Compte",
        my_account_save: "Enregistrer",
        address_title: "Adresse",
        address_label: "Adresse",
        address_save: "Enregistrer",
        order_overview: "Aperçu de la commande",
        shipping_to: "Expédition vers",
        subtotal: "Sous-total",
        shipping_cost: "Frais de port",
        order_total: "Total",
        free_shipping: "🎉 Livraison gratuite!",
        free_shipping_info: "💡 Encore €{amount} pour la livraison gratuite!",
        confirm_order: "✅ Confirmer la commande",
        edit_address: "✏️ Modifier l'adresse",
        order_confirmed: "🎉 Commande confirmée!",
        order_number: "Numéro de commande",
        order_success_text: "Votre commande a été reçue et est en cours de traitement.",
        email_confirmation: "📧 Une confirmation sera envoyée à:",
        shipping_info_text: "📦 Expédition:",
        close_btn: "Fermer"
      },
      de: {
        title: "Doctor Vinyl Records",
        nav_home: "Startseite",
        nav_records: "Schallplatten",
        nav_specials: "Angebote",
        nav_about: "Über uns",
        nav_contact: "Kontakt",
        nav_sales: "Verkäufe",
        nav_login: "Anmelden",
        search_placeholder: "Suchen...",
        sales_title: "Verkäufe",
        sale_badge: "ANGEBOT",
        add_to_cart: "In den Warenkorb",
        hero_title: "Doctor Vinyl Records",
        hero_subtitle: "Vinyl-Spezialist in Brüssel – Neue & gebrauchte Schallplatten, Spezialangebote & mehr",
        records_title: "Alle Schallplatten",
        specials_title: "Spezialangebote & Eigenproduktionen",
        about_title: "Über uns / News",
        about_text: "DOCTOR VINYL, im Herzen von Brüssel gelegen, ist einer der Pionier-Plattenläden in Belgien, spezialisiert auf elektronische Musik. Ein Leuchtturm für Liebhaber elektronischer Musik, unser kleiner und gemütlicher Shop ist ein Zufluchtsort für alle, die den authentischen warmen analogen Sound suchen. Bei Doctor Vinyl sind wir stolz auf unsere Sammlung gebrauchter und gelegentlich neuer Vinyl-Platten, die sorgfältig organisiert und ausgewählt sind. Als Entdecker neuer Grooves bieten wir ein vielfältiges Spektrum an Unterkategorien der elektronischen Musik, darunter House, Techno, D&B, Nu Beat, Industrial, Experimental und alles dazwischen. Unser Shop ist nicht nur ein Ort zum Plattenkauf; es ist ein Raum, wo Musikliebhaber zusammenkommen, um ihre Leidenschaft zu teilen. Unser freundliches und sachkundiges Team begleitet Sie gerne und sorgt dafür, dass jeder Besuch ein einzigartiges und bereicherndes Erlebnis wird. Als einer der ersten Betriebe seiner Art in Belgien ist Doctor Vinyl zu einem Eckpfeiler im kulturellen Gefüge von Brüssel geworden. Treten Sie ein in unsere Welt, wo das Knistern von Vinyl und der Puls elektronischer Beats zu einem unvergesslichen Einkaufserlebnis verschmelzen.",
        contact_title: "Kontakt",
        contact_address: "Groot Eiland 1\n1000 Brüssel",
        contact_phone: "+32 476 71 75 40",
        contact_mail: "info@doctorvinyl.be",
        cart_title: "Warenkorb",
        cart_total: "Gesamt:",
        cart_clear: "Warenkorb leeren",
        checkout: "Zur Kasse",
        login_title: "Anmelden",
        login_username: "E-Mail",
        login_password: "Passwort",
        login_btn: "Anmelden",
        register_link: "Noch kein Konto? Registrieren",
        register_title: "Registrieren",
        register_username: "E-Mail",
        register_password: "Passwort",
        register_password_confirm: "Passwort bestätigen",
        register_lastname: "Nachname",
        register_firstname: "Vorname",
        register_street: "Straße",
        register_number: "Hausnummer",
        register_app: "Wohnung",
        register_postal: "Postleitzahl",
        register_city: "Stadt",
        register_country: "Land",
        register_address: "Adresse",
        register_btn: "Registrieren",
        register_username_placeholder: "E-Mail",
        register_password_placeholder: "Passwort",
        register_password_confirm_placeholder: "Passwort bestätigen",
        register_lastname_placeholder: "Nachname",
        register_firstname_placeholder: "Vorname",
        register_street_placeholder: "Straße",
        register_number_placeholder: "Hausnummer",
        register_app_placeholder: "Wohnung",
        register_postal_placeholder: "z.B. 1000",
        register_city_placeholder: "Stadt",
        register_country_placeholder: "Land",
        my_account_btn: "Mein Konto",
        my_account_title: "Mein Konto",
        my_account_save: "Speichern",
        address_title: "Adressdaten",
        address_label: "Adresse",
        address_save: "Speichern",
        order_overview: "Bestellübersicht",
        shipping_to: "Versand nach",
        subtotal: "Zwischensumme",
        shipping_cost: "Versandkosten",
        order_total: "Gesamt",
        free_shipping: "🎉 Kostenloser Versand!",
        free_shipping_info: "💡 Noch €{amount} für kostenlosen Versand!",
        confirm_order: "✅ Bestellung bestätigen",
        edit_address: "✏️ Adresse bearbeiten",
        order_confirmed: "🎉 Bestellung bestätigt!",
        order_number: "Bestellnummer",
        order_success_text: "Ihre Bestellung wurde erhalten und wird bearbeitet.",
        email_confirmation: "📧 Eine Bestätigung wird gesendet an:",
        shipping_info_text: "📦 Versand:",
        close_btn: "Schließen"
      }
    };

    function setLang(lang) {
      document.documentElement.lang = lang;
      // Teksten
      document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) el.textContent = translations[lang][key];
      });
      // Placeholders
      document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[lang][key]) el.placeholder = translations[lang][key];
      });
    }

    // Language switcher events for <select> dropdowns
    document.addEventListener('DOMContentLoaded', function() {
      var langSelect = document.getElementById('langSelect');
      if (langSelect) {
        langSelect.addEventListener('change', function() {
          setLang(this.value);
        });
      }
      var mobileLangSelect = document.getElementById('mobileLangSelect');
      if (mobileLangSelect) {
        mobileLangSelect.addEventListener('change', function() {
          setLang(this.value);
        });
      }
      // Set default language and dropdowns
      setLang('en');
      if (langSelect) langSelect.value = 'en';
      if (mobileLangSelect) mobileLangSelect.value = 'en';
    });